### ISSUE TITLE
How would one reach out to yall?

### ISSUE THREAD

**Issue by rspforhp** [n2g7mutf8/SexyAppFramework#2]
To talk and maybe help deving, i have a lot of experience with this engine

**Comment by YalekW5435** [comment]
I need to get push access for you first.

**Comment by YalekW5435** [comment]
If you want you can message me on telegram if youd like

**Comment by rspforhp** [comment]
do u like have discord or smth?

**Comment by YalekW5435** [comment]
Im only using discord to accept certain people.  But i can friends ya there just a sec.
Whats your display name..?

**Comment by rspforhp** [comment]
miya_kopie

**Comment by rspforhp** [comment]
whats urs?

**Comment by YalekW5435** [comment]
just added ya...

**Comment by rspforhp** [comment]
https://cdn.discordapp.com/attachments/1128401715419414580/1181682818045186129/image.png?ex=6581f2e2&is=656f7de2&hm=fa22a597089ce19e1c633ab39a42856950002d40dcafb42bed0560c06ae57ca2&

**Comment by rspforhp** [comment]
Found the sexyappframework dev, randomly, was looking for cool programming languages, and found his, apparently the lib he made in his language is a evolution of the popcap framework

**Comment by YalekW5435** [comment]
The biggest problem is Beefy is too much like C#.  Unless if he has a C++ copy somewhere, then I can use it.  
Not that I dont know how it works, but I know C# too.

**Comment by YalekW5435** [comment]
Also Miya, I kinda didnt like the way our conversations went in DMs, so I would highly suggest not DMing me on discord.  You showed mental instability and, in my interperetation of how you ranted, "felt annoyed and verbally harassed".  Especially coming from a 16 year old minor.  Remember im 10 years older than you and have much more knowledge of popcap (since 2002).  Please respect my wishes with those starements.

**Comment by rspforhp** [comment]
the beefy gui is fully made in c++

**Comment by rspforhp** [comment]
also i do have more knowledge about popcap than u huh

**Comment by rspforhp** [comment]
i didnt feel annoyed nor verbally harassed, u just kept msging me while i was working lol

**Comment by YalekW5435** [comment]
You couldve easily told me those things and I wouldnt have to put up the block that I did.  
You may have knowledge of programming but thats not my stronghold yet.  

"i didnt feel annoyed nor verbally harassed, u just kept msging me while i was working lol".
Lets re-instate the cooperation, then.  Just remind me when to leave you alone while your working.

**Comment by rspforhp** [comment]
k
